#!/usr/bin/env python3
"""Sync canonical backlog-howto skill into Python/TS/Go generated constants."""

from __future__ import annotations

from datetime import datetime, UTC
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
CANONICAL = ROOT / "bl_skills" / "backlog-howto" / "SKILL.md"

PY_OUT = ROOT / "backlog" / "commands" / "generated_backlog_howto.py"
TS_OUT = ROOT / "backlog_ts" / "src" / "generated" / "backlogHowtoSkill.ts"
GO_OUT = ROOT / "backlog_go" / "internal" / "skills" / "backlog_howto_generated.go"

VERSION_PATTERN = re.compile(r"^Skill-Version:\s*(.+)$", re.MULTILINE)


def _now_version() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _stamp_version(text: str, version: str) -> str:
    if not VERSION_PATTERN.search(text):
        raise ValueError("Skill-Version marker not found in canonical SKILL.md")
    return VERSION_PATTERN.sub(f"Skill-Version: {version}", text, count=1)


def _read_version(text: str) -> str:
    match = VERSION_PATTERN.search(text)
    if not match:
        raise ValueError("Skill-Version marker not found after update")
    return match.group(1).strip()


def _write_python(skill_text: str, version: str) -> None:
    content = (
        '"""Generated by bl_skills/sync_backlog_howto.py. Do not edit manually."""\n\n'
        f'BACKLOG_HOWTO_SKILL_VERSION = "{version}"\n'
        f"BACKLOG_HOWTO_SKILL_MD = {skill_text!r}\n"
    )
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.write_text(content, encoding="utf-8")


def _write_ts(skill_text: str, version: str) -> None:
    escaped = skill_text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    content = (
        "// Generated by bl_skills/sync_backlog_howto.py. Do not edit manually.\n"
        f'export const BACKLOG_HOWTO_SKILL_VERSION = "{version}";\n'
        f"export const BACKLOG_HOWTO_SKILL_MD = `{escaped}`;\n"
    )
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(content, encoding="utf-8")


def _write_go(skill_text: str, version: str) -> None:
    if "`" in skill_text:
        raise ValueError("Go raw string generation requires canonical skill without backticks")
    content = (
        "// Code generated by bl_skills/sync_backlog_howto.py; DO NOT EDIT.\n\n"
        "package skills\n\n"
        f'const BacklogHowtoSkillVersion = "{version}"\n\n'
        "const BacklogHowtoSkillMD = `"
        + skill_text
        + "`\n"
    )
    GO_OUT.parent.mkdir(parents=True, exist_ok=True)
    GO_OUT.write_text(content, encoding="utf-8")


def main() -> None:
    canonical = CANONICAL.read_text(encoding="utf-8")
    stamped = _stamp_version(canonical, _now_version())
    CANONICAL.write_text(stamped, encoding="utf-8")

    version = _read_version(stamped)
    _write_python(stamped, version)
    _write_ts(stamped, version)
    _write_go(stamped, version)
    print(f"Synced backlog-howto skill version {version}")


if __name__ == "__main__":
    main()
