package commands

// TODO: implement CLI command handlers for parity with Python/TypeScript implementations.

// CommandName declares supported command identifiers for the Go implementation.
const (
	CmdInit     = "init"
	CmdLog      = "log"
	CmdTree     = "tree"
	CmdDash     = "dash"
	CmdList     = "list"
	CmdLs       = "ls"
	CmdSearch   = "search"
	CmdCheck    = "check"
	CmdReport   = "report"
	CmdTimeline = "timeline"
	CmdTimelineAlias = "tl"
	CmdReportAlias = "r"
	CmdBlockers = "blockers"
	CmdWhy      = "why"
	CmdAdmin    = "admin"
	CmdNext     = "next"
	CmdPreview  = "preview"
	CmdShow     = "show"
	CmdAdd      = "add"
	CmdAddEpic      = "add-epic"
	CmdAddMilestone = "add-milestone"
	CmdAddPhase     = "add-phase"
	CmdSet          = "set"
	CmdUnclaim      = "unclaim"
	CmdSync         = "sync"
	CmdUpdate       = "update"
	CmdUndone       = "undone"
	CmdGrab     = "grab"
	CmdGrant    = CmdGrab
	CmdGrants   = "grants"
	CmdClaim    = "claim"
	CmdDone     = "done"
	CmdCycle    = "cycle"
	CmdWork     = "work"
	CmdMove     = "move"
	CmdHelp     = "help"
	CmdVersion  = "version"
	CmdSprint   = "sprint"
	CmdUnknown  = "unknown"
)
