package commands

// TODO: implement CLI command handlers for parity with Python/TypeScript implementations.

// CommandName declares supported command identifiers for the Go implementation.
const (
	CmdInit          = "init"
	CmdLog           = "log"
	CmdTree          = "tree"
	CmdDash          = "dash"
	CmdList          = "list"
	CmdLs            = "ls"
	CmdSearch        = "search"
	CmdCheck         = "check"
	CmdData          = "data"
	CmdSchema        = "schema"
	CmdSession       = "session"
	CmdSkills        = "skills"
	CmdHowto         = "howto"
	CmdAgents        = "agents"
	CmdReport        = "report"
	CmdTimeline      = "timeline"
	CmdTimelineAlias = "tl"
	CmdReportAlias   = "r"
	CmdBlockers      = "blockers"
	CmdBlocked       = "blocked"
	CmdWhy           = "why"
	CmdBenchmark     = "benchmark"
	CmdAdmin         = "admin"
	CmdNext          = "next"
	CmdPreview       = "preview"
	CmdShow          = "show"
	CmdAdd           = "add"
	CmdAddEpic       = "add-epic"
	CmdAddMilestone  = "add-milestone"
	CmdAddPhase      = "add-phase"
	CmdSet           = "set"
	CmdUnclaim       = "unclaim"
	CmdSync          = "sync"
	CmdUpdate        = "update"
	CmdUndone        = "undone"
	CmdGrab          = "grab"
	CmdGrant         = CmdGrab
	CmdGrants        = "grants"
	CmdClaim         = "claim"
	CmdDone          = "done"
	CmdCycle         = "cycle"
	CmdWork          = "work"
	CmdSkip          = "skip"
	CmdHandoff       = "handoff"
	CmdUnclaimStale  = "unclaim-stale"
	CmdMove          = "move"
	CmdLock          = "lock"
	CmdUnlock        = "unlock"
	CmdIdea          = "idea"
	CmdBug           = "bug"
	CmdFixed         = "fixed"
	CmdMigrate       = "migrate"
	CmdHelp          = "help"
	CmdVersion       = "version"
	CmdSprint        = "sprint"
	CmdUnknown       = "unknown"
)
